"""empty message

Revision ID: b06dd4d19484
Revises: 74db324b2765
Create Date: 2020-02-25 12:39:47.352210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06dd4d19484'
down_revision = '74db324b2765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('company_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('company_website', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('company_location', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('company_socialmedia', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('company_name', name='company_pkey')
    )
    # ### end Alembic commands ###
